version: '3'
services:
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
  scheduler:
    build: .
    command: python scheduler.py
    depends_on:
      - redis
